/**
 * Source-backed Malaysian advertising rule pack.
 *
 * This pack deliberately keeps nationwide online-content rules separate from
 * local-authority physical advertising rules. It is not legal advice and must
 * be reviewed when a source is amended.
 */

const CONTENT_CODE = "https://contentforum.my/wp-content/uploads/2024/01/Content-Code-2022.pdf";
const KPDN_GUIDE = "https://repositori.kpdn.gov.my/bitstream/123456789/5347/1/Buku%20Garis%20Panduan%20Mengelakkan%20Iklan%20Palsu%20atau%20Mengelirukan%20Dalam%20Talian.pdf";
const KPDN_ACTS = "https://www.kpdn.gov.my/en/public?catid=20%3Ahome&id=187%3Aakta-peraturan-garis-panduan&view=article";
const DBKL_ADVERTISING = "https://www.dbkl.gov.my/jabatan/jabatan-pelesenan-dan-pembangunan-perniagaan";

const ONLINE_SCOPE = "Malaysia — electronic networked advertising and marketing communications. This is a Content Code self-regulatory screening rule; product-specific laws and platform policy may impose additional requirements.";

export const MALAYSIA_RULE_PACK = [
  {
    id: "MY-CODE2022-001",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §§3.1 and 4.2",
    category: "Online advertising — general principles",
    rule_title: "Advertising must be legal, decent, honest and truthful",
    evidence_urls: [CONTENT_CODE],
    rule_text: "Screen advertising and marketing communications for legality, decency, honesty, truthfulness, consumer rights and the product-specific laws that apply. This rule is a self-regulatory content standard, not an automated legal determination.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|self-regulatory|general-principles",
  },
  {
    id: "MY-CODE2022-002",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §4.3",
    category: "Online advertising — decency and sensitivity",
    rule_title: "Avoid serious or widespread offence and respect audience sensitivities",
    evidence_urls: [CONTENT_CODE],
    rule_text: "Flag content likely to cause serious or widespread offence, including on grounds such as race, religion, sex, sexual orientation, or physical or mental disability. Assess the likely audience and context; mere product offence is not by itself decisive.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|decency|race|religion|sensitivity",
  },
  {
    id: "MY-CODE2022-003",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §§4.4 and 4.8",
    category: "Online advertising — misleading claims and substantiation",
    rule_title: "Do not mislead; retain substantiation for objectively verifiable claims",
    evidence_urls: [CONTENT_CODE, KPDN_GUIDE, KPDN_ACTS],
    rule_text: "Flag claims or presentations likely to mislead through inaccuracy, ambiguity, exaggeration, falsehood, omission, or hidden material information. Objective descriptions, claims and comparisons should be capable of substantiation that the advertiser can produce when requested.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|kpdn|consumer-protection|claims|substantiation|misleading",
  },
  {
    id: "MY-CODE2022-004",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §§4.10 and 4.12",
    category: "Online advertising — prices and promotions",
    rule_title: "State prices and material promotion terms clearly",
    evidence_urls: [CONTENT_CODE, KPDN_GUIDE, KPDN_ACTS],
    rule_text: "Flag price or promotion copy that could leave a consumer guessing about the final payable price, mandatory charges, qualifying conditions, availability, material limitations, or whether a stated discount is real. Check the offer against its actual terms before publishing.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|kpdn|price|promotion|discount|material-information",
  },
  {
    id: "MY-CODE2022-005",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §6.1",
    category: "Online advertising — ad identification",
    rule_title: "Make advertisements recognisable and disclose virtual influencers",
    evidence_urls: [CONTENT_CODE],
    rule_text: "Advertising, including lead-in advertising, should be designed and presented so that it is clear it is an advertisement. If a virtual influencer is used in an advertisement, disclose that it is virtual so consumers are not misled into believing they are interacting with a real human.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|advertising-disclosure|virtual-influencer|ai",
  },
  {
    id: "MY-CODE2022-006",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §§6.2–6.4",
    category: "Online advertising — paid endorsements",
    rule_title: "Clearly disclose paid endorsements and sponsored content",
    evidence_urls: [CONTENT_CODE],
    rule_text: "For marketing communications made under payment or another reciprocal arrangement, require clear identification as advertising. For paid endorsements, use an upfront understandable label with the endorsement; avoid vague shorthand; use the endorsement language; place a video disclosure in the video itself; repeat disclosure periodically in a live stream.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|influencer|sponsored|paid-partnership|disclosure",
  },
  {
    id: "MY-CODE2022-007",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §7",
    category: "Online advertising — children",
    rule_title: "Apply heightened safeguards to advertising involving or targeting children",
    evidence_urls: [CONTENT_CODE],
    rule_text: "Flag advertising addressed to or likely to be seen by children when it exploits credulity, loyalty, vulnerability, or inexperience; promotes unsafe conduct; directly exhorts a child to buy or persuade others to buy; or portrays children in sexual, harmful, or unsafe ways. The ad style should be appropriate for its primary audience.",
    applies_to: ONLINE_SCOPE,
    enforcement: "self_regulatory_review",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|children|minors|safety|targeting",
  },
  {
    id: "MY-CODE2022-008",
    source: "malaysia",
    regulator: "Communications and Multimedia Content Forum of Malaysia (Content Forum)",
    framework: "Malaysian Communications and Multimedia Content Code 2022, Part 3 §§4.7 and 4.16",
    category: "Online advertising — illegal and unsafe conduct",
    rule_title: "Do not promote illegal, unsafe, or prohibited products and conduct",
    evidence_urls: [CONTENT_CODE],
    rule_text: "Flag content that condones, provokes, or glorifies violence, unlawful, or anti-social behaviour; encourages unsafe practices; or advertises a product or service prohibited under applicable Malaysian law. Product-specific legal status must be verified separately before a hard rejection is made.",
    applies_to: ONLINE_SCOPE,
    enforcement: "product_law_review_required",
    effective_date: "2022-05-30",
    last_updated: "2026-07-30",
    tags: "malaysia|online|content-code-2022|illegal|unsafe|violence|product-law",
  },
  {
    id: "MY-KPDN-2025-001",
    source: "malaysia",
    regulator: "Ministry of Domestic Trade and Cost of Living (KPDN)",
    framework: "Consumer Protection Act 1999 (Act 599); KPDN online false-or-misleading advertising guidance",
    category: "Online commerce — consumer representations",
    rule_title: "Review online commercial claims for false or misleading representations",
    evidence_urls: [KPDN_GUIDE, KPDN_ACTS],
    rule_text: "For consumer-facing online advertising, review claims, price statements, promotions, material qualifications, and visual presentations for false or misleading representations. This is a consumer-protection screening rule; it does not replace assessment under the Consumer Protection Act 1999 or product-specific laws.",
    applies_to: "Malaysia — consumer-facing online commercial advertising and transactions. KPDN is the relevant consumer-protection authority.",
    enforcement: "consumer_protection_review",
    effective_date: "1999-11-15",
    last_updated: "2026-07-30",
    tags: "malaysia|kpdn|consumer-protection-act-1999|online-commerce|false-or-misleading",
  },
  {
    id: "MY-DBKL-OUTDOOR-001",
    source: "outdoor_dbkl",
    regulator: "Dewan Bandaraya Kuala Lumpur (DBKL)",
    framework: "DBKL Advertisement Licence FAQ and DBKL Licensing Guidelines Amendment 2023",
    category: "Physical advertising — DBKL licence scope",
    rule_title: "Billboards and outdoor displays in DBKL require local licence review",
    evidence_urls: [DBKL_ADVERTISING],
    rule_text: "For a physical advertisement located within DBKL's administrative area, require a DBKL advertisement-licence review. DBKL identifies outdoor formats including billboards, LED displays, wall, sky, flyover/bridge and gantry advertising, and publishes location, structural, ownership/permission and insurance documentation requirements by format.",
    applies_to: "Kuala Lumpur only — this is a DBKL local-authority licensing rule, not a Malaysia-wide billboard rule. Obtain the relevant PBT's requirements for every other location.",
    enforcement: "local_licence_review_required",
    effective_date: "2024-08-28",
    last_updated: "2026-07-30",
    tags: "malaysia|kuala-lumpur|dbkl|outdoor|billboard|licence|local-authority",
  },
  {
    id: "MY-DBKL-OUTDOOR-002",
    source: "outdoor_dbkl",
    regulator: "Dewan Bandaraya Kuala Lumpur (DBKL)",
    framework: "DBKL Advertisement Licence FAQ and DBKL Licensing Guidelines Amendment 2023",
    category: "Physical advertising — DBKL content and language",
    rule_title: "DBKL advertising-licence applications require local language and content checks",
    evidence_urls: [DBKL_ADVERTISING],
    rule_text: "For DBKL advertising-licence applications, visual design should prioritise Bahasa Melayu in word size, colour and position. DBKL states that advertising liquor, tobacco, suggestive imagery, or indecent/obscene conduct is not permitted, and that Bahasa Malaysia usage should be referred to Dewan Bahasa dan Pustaka for verification before applying.",
    applies_to: "Kuala Lumpur only — applies to DBKL advertisement licensing. Do not apply this rule outside DBKL without the relevant PBT's published requirement.",
    enforcement: "local_licence_review_required",
    effective_date: "2024-08-28",
    last_updated: "2026-07-30",
    tags: "malaysia|kuala-lumpur|dbkl|outdoor|bahasa-melayu|licence|content",
  },
];

/** Old rows to keep for audit only. They are not deleted; the sync moves them
 * out of the `malaysia` source so the evaluator cannot treat stale assertions
 * as an active nationwide rule. */
export const LEGACY_MALAYSIA_RULE_IDS = [
  "MY-ASA-001", "MY-ASA-002", "MY-ASA-003", "MY-ASA-004", "MY-ASA-005",
  "MY-ASA-006", "MY-ASA-007", "MY-ASA-008", "MY-ASA-009", "MY-ASA-010",
  "MY-ASA-011", "MY-ASA-012", "MY-KPDNHEP-001", "MY-KPDNHEP-002",
  "MY-MCMC-ADV-001", "MY-MCMC-ADV-002", "MY-MCMC-ADV-003", "MY-MDA-001",
  "MY-CRYPTO-001",
];
