"""
video_assembler.py
──────────────────
Dual-output video assembly: FFmpeg (.mp4) + CapCut (editable draft).

This module takes a list of scene clips (generated by Veo I2V) and assembles
them into a final video via TWO paths simultaneously:

1. FFmpeg → renders an instant .mp4 with transitions, subtitles, audio mix
2. pyCapCut → creates an editable CapCut draft the user can open and fine-tune

The AI decides WHAT edits to apply (transitions, text timing, speed) based on
the scene content. The user gets instant preview + the ability to refine.

Called from video_v2.py after scene clips are generated.
"""

import json
import logging
import os
import subprocess
import tempfile
from typing import Optional

logger = logging.getLogger(__name__)

FFMPEG_BIN = os.environ.get("FFMPEG_BIN", "ffmpeg")


# ─────────────────────────────────────────────────────────────────────────────
# AI Edit Planner — Gemini decides what edits to apply per scene
# ─────────────────────────────────────────────────────────────────────────────

_EDIT_PLANNER_PROMPT = """You are a professional video editor AI. Given a scene list for a short ad video, decide what post-production edits each scene needs.

SCENES:
{scenes_json}

For each scene, decide:
- transition_in: what transition to use entering this scene ("none" for first scene, then "crossfade", "fade_black", "wipe_left", "cut", "zoom_in")
- transition_duration: seconds (0.3-1.0)
- speed_factor: playback speed (1.0 = normal, 1.2 = slightly fast for energy, 0.8 = slow-mo for drama)
- text_overlay: the subtitle text to burn in (from the scene data)
- text_position: where to put text ("bottom", "center", "top")
- text_timing: when to show text relative to scene start ("immediate", "delayed_1s", "last_2s")

Rules:
- First scene: NO transition_in (it's the opener), speed can be 1.0-1.3 for energy
- Hook scenes (first 1-2): fast pacing, text appears immediately, bold
- Product scenes (middle): normal speed, text at bottom
- CTA scene (last): slightly slower, text at center for emphasis
- Keep total edits SIMPLE — this is a short ad, not a film

Return ONLY a JSON array of objects matching the scene count.
Each object: {{"transition_in": "...", "transition_duration": 0.5, "speed_factor": 1.0, "text_overlay": "...", "text_position": "bottom", "text_timing": "immediate"}}"""


async def plan_edits(scenes: list[dict]) -> list[dict]:
    """Ask Gemini to decide what edits each scene needs.

    Args:
        scenes: List of scene dicts with description, subtitle, duration, etc.

    Returns:
        List of edit decisions per scene. Falls back to defaults on failure.
    """
    from shared.clients import gemini

    if not gemini:
        return _default_edit_plan(scenes)

    try:
        from google.genai import types as genai_types

        scenes_summary = [
            {
                "scene_index": i + 1,
                "description": s.get("description", "")[:100],
                "subtitle": s.get("subtitle", ""),
                "duration": s.get("duration", 5),
                "is_hook": i < 2,
                "is_cta": i == len(scenes) - 1,
            }
            for i, s in enumerate(scenes)
        ]

        response = gemini.models.generate_content(
            model="gemini-2.5-flash",
            contents=_EDIT_PLANNER_PROMPT.format(scenes_json=json.dumps(scenes_summary, indent=2)),
            config=genai_types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.2,
            ),
        )

        edits = json.loads(response.text)
        if isinstance(edits, list) and len(edits) == len(scenes):
            logger.info("[VideoAssembler] AI planned edits for %d scenes", len(edits))
            return edits

        logger.warning("[VideoAssembler] AI returned wrong edit count, using defaults")
        return _default_edit_plan(scenes)

    except Exception as e:
        logger.error("[VideoAssembler] AI edit planning failed: %s — using defaults", e)
        return _default_edit_plan(scenes)


def _default_edit_plan(scenes: list[dict]) -> list[dict]:
    """Deterministic fallback edit plan when Gemini is unavailable."""
    edits = []
    for i, scene in enumerate(scenes):
        is_first = i == 0
        is_last = i == len(scenes) - 1

        edits.append({
            "transition_in": "none" if is_first else "crossfade",
            "transition_duration": 0.0 if is_first else 0.5,
            "speed_factor": 1.0,
            "text_overlay": scene.get("subtitle", ""),
            "text_position": "center" if is_last else "bottom",
            "text_timing": "immediate",
        })
    return edits


# ─────────────────────────────────────────────────────────────────────────────
# FFmpeg Assembly — renders instant .mp4
# ─────────────────────────────────────────────────────────────────────────────


def assemble_ffmpeg(
    scene_clips: list[str],
    edit_plan: list[dict],
    audio_path: Optional[str] = None,
    output_path: Optional[str] = None,
) -> Optional[str]:
    """Assemble scene clips into a final .mp4 using FFmpeg.

    Applies the AI's edit decisions: transitions between clips, speed changes,
    and text overlays (subtitles).

    Args:
        scene_clips: Ordered list of scene video file paths.
        edit_plan: AI-generated edit decisions per scene.
        audio_path: Optional voiceover/music audio to mix in.
        output_path: Where to save the final .mp4 (auto-generated if None).

    Returns:
        Path to the assembled .mp4 file, or None on failure.
    """
    if not scene_clips:
        logger.error("[VideoAssembler] No scene clips to assemble")
        return None

    if output_path is None:
        output_path = os.path.join(tempfile.gettempdir(), f"assembled_{os.getpid()}.mp4")

    # Step 1: Apply per-scene speed changes and text overlays
    processed_clips = []
    for i, clip_path in enumerate(scene_clips):
        if not os.path.exists(clip_path):
            logger.warning("[VideoAssembler] Scene clip missing: %s", clip_path)
            continue

        edit = edit_plan[i] if i < len(edit_plan) else {}
        speed = edit.get("speed_factor", 1.0)
        text = edit.get("text_overlay", "")
        position = edit.get("text_position", "bottom")

        processed = _apply_scene_edits(clip_path, i, speed, text, position)
        if processed:
            processed_clips.append(processed)
        else:
            processed_clips.append(clip_path)  # Use original on failure

    if not processed_clips:
        return None

    # Step 2: Concatenate with transitions
    if len(processed_clips) == 1:
        final_video = processed_clips[0]
    else:
        final_video = _concat_with_transitions(processed_clips, edit_plan)

    if not final_video:
        return None

    # Step 3: Mix audio if provided
    if audio_path and os.path.exists(audio_path):
        mixed = _mix_audio(final_video, audio_path, output_path)
        if mixed:
            return mixed

    # No audio or mix failed — copy/move the video to output
    if final_video != output_path:
        try:
            import shutil
            shutil.copy2(final_video, output_path)
        except Exception:
            return final_video

    return output_path


def _apply_scene_edits(
    clip_path: str, scene_index: int, speed: float, text: str, position: str
) -> Optional[str]:
    """Apply speed change and text overlay to a single scene clip."""
    out_path = os.path.join(tempfile.gettempdir(), f"scene_edited_{scene_index}.mp4")
    filters = []

    # Speed filter
    if speed != 1.0 and 0.25 <= speed <= 4.0:
        filters.append(f"setpts={1.0/speed}*PTS")

    # Text overlay
    if text:
        safe_text = text.replace("'", "\\'").replace(":", "\\:").replace(",", "\\,")
        y_map = {"top": "h*0.1", "center": "(h-text_h)/2", "bottom": "h*0.85"}
        y_expr = y_map.get(position, "h*0.85")

        font_clause = ""
        if os.name == "nt":
            font_clause = ":fontfile=C\\\\:/Windows/Fonts/arial.ttf"

        filters.append(
            f"drawtext=text='{safe_text}'{font_clause}"
            f":fontsize=36:fontcolor=white"
            f":x=(w-text_w)/2:y={y_expr}"
            f":box=1:boxcolor=black@0.5:boxborderw=8"
        )

    if not filters:
        return None  # No edits needed, use original

    filter_str = ",".join(filters)

    # Build audio filter for speed
    audio_filters = []
    if speed != 1.0 and 0.25 <= speed <= 4.0:
        if speed > 2.0:
            audio_filters.append(f"atempo=2.0,atempo={speed/2.0}")
        elif speed < 0.5:
            audio_filters.append(f"atempo=0.5,atempo={speed/0.5}")
        else:
            audio_filters.append(f"atempo={speed}")

    cmd = [FFMPEG_BIN, "-y", "-i", clip_path]
    if audio_filters:
        cmd += ["-filter_complex", f"[0:v]{filter_str}[v];[0:a]{','.join(audio_filters)}[a]"]
        cmd += ["-map", "[v]", "-map", "[a]"]
    else:
        cmd += ["-vf", filter_str, "-c:a", "copy"]
    cmd.append(out_path)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode == 0:
            return out_path
        logger.warning("[VideoAssembler] Scene %d edit failed: %s", scene_index, result.stderr[-200:])
    except Exception as e:
        logger.warning("[VideoAssembler] Scene %d edit error: %s", scene_index, e)

    return None


def _concat_with_transitions(clips: list[str], edit_plan: list[dict]) -> Optional[str]:
    """Concatenate clips with cross-fade transitions between them."""
    if len(clips) < 2:
        return clips[0] if clips else None

    out_path = os.path.join(tempfile.gettempdir(), f"concat_transitions_{os.getpid()}.mp4")

    # Simple approach: concat via demuxer (fast, no re-encode for most cases)
    # For transitions, we use xfade between consecutive pairs
    current = clips[0]

    for i in range(1, len(clips)):
        next_clip = clips[i]
        edit = edit_plan[i] if i < len(edit_plan) else {}
        transition = edit.get("transition_in", "crossfade")
        t_dur = edit.get("transition_duration", 0.5)

        if transition == "none" or transition == "cut":
            # Simple concat without transition
            pair_out = os.path.join(tempfile.gettempdir(), f"pair_{i}_{os.getpid()}.mp4")
            _simple_concat([current, next_clip], pair_out)
            current = pair_out
        else:
            # xfade transition
            pair_out = os.path.join(tempfile.gettempdir(), f"xfade_{i}_{os.getpid()}.mp4")
            xfade_type = _map_transition_to_ffmpeg(transition)

            # Get duration of current clip for offset calculation
            dur = _get_duration(current)
            if dur is None:
                dur = 5.0
            offset = max(0, dur - t_dur)

            cmd = [
                FFMPEG_BIN, "-y", "-i", current, "-i", next_clip,
                "-filter_complex",
                f"[0:v][1:v]xfade=transition={xfade_type}:duration={t_dur}:offset={offset}[v];"
                f"[0:a][1:a]acrossfade=d={t_dur}[a]",
                "-map", "[v]", "-map", "[a]", pair_out,
            ]

            try:
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
                if result.returncode == 0:
                    current = pair_out
                else:
                    # Fallback: simple concat
                    _simple_concat([current, next_clip], pair_out)
                    current = pair_out
            except Exception:
                _simple_concat([current, next_clip], pair_out)
                current = pair_out

    # Copy final result to output path
    if current != out_path:
        try:
            import shutil
            shutil.copy2(current, out_path)
        except Exception:
            return current

    return out_path


def _mix_audio(video_path: str, audio_path: str, output_path: str) -> Optional[str]:
    """Mix voiceover/music audio onto the assembled video."""
    cmd = [
        FFMPEG_BIN, "-y", "-i", video_path, "-i", audio_path,
        "-filter_complex",
        "[0:a]volume=0.3[bg];[bg][1:a]amix=inputs=2:duration=first[a]",
        "-map", "0:v", "-map", "[a]", "-c:v", "copy", "-shortest",
        output_path,
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0:
            return output_path
        logger.warning("[VideoAssembler] Audio mix failed: %s", result.stderr[-200:])
    except Exception as e:
        logger.warning("[VideoAssembler] Audio mix error: %s", e)

    return None


def _simple_concat(parts: list[str], output_path: str) -> bool:
    """Simple FFmpeg concat demuxer (no re-encoding)."""
    concat_list = os.path.join(tempfile.gettempdir(), f"concat_{os.getpid()}.txt")
    with open(concat_list, "w") as f:
        for p in parts:
            f.write(f"file '{p.replace(os.sep, '/')}'\n")

    cmd = [FFMPEG_BIN, "-y", "-f", "concat", "-safe", "0", "-i", concat_list, "-c", "copy", output_path]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        os.remove(concat_list)
        return result.returncode == 0
    except Exception:
        return False


def _map_transition_to_ffmpeg(transition: str) -> str:
    """Map AI transition names to FFmpeg xfade transition types."""
    mapping = {
        "crossfade": "fade",
        "fade_black": "fadeblack",
        "wipe_left": "wipeleft",
        "wipe_right": "wiperight",
        "zoom_in": "circlecrop",
        "dissolve": "dissolve",
        "slide_left": "slideleft",
        "slide_right": "slideright",
    }
    return mapping.get(transition, "fade")


def _get_duration(path: str) -> Optional[float]:
    """Get media duration in seconds."""
    try:
        cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration",
               "-of", "default=noprint_wrappers=1:nokey=1", path]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            return float(result.stdout.strip())
    except Exception:
        pass
    return None


# ─────────────────────────────────────────────────────────────────────────────
# CapCut Draft Assembly — creates editable project
# ─────────────────────────────────────────────────────────────────────────────


def assemble_capcut_draft(
    scene_clips: list[str],
    edit_plan: list[dict],
    scenes: list[dict],
    audio_path: Optional[str] = None,
    subtitles_srt: Optional[str] = None,
    draft_name: str = "ai_video_ad",
    width: int = 1080,
    height: int = 1920,
    capcut_drafts_folder: Optional[str] = None,
) -> Optional[dict]:
    """Create an editable CapCut draft from scene clips + AI edit plan.

    This is the second output alongside FFmpeg. The user can open this draft
    in CapCut desktop to adjust transitions, text styling, timing, and add
    effects — then export at full quality from CapCut.

    Args:
        scene_clips: Ordered list of rendered scene clip paths.
        edit_plan: AI edit decisions per scene.
        scenes: Original scene data (descriptions, subtitles, etc.)
        audio_path: Optional voiceover audio file.
        subtitles_srt: Optional .srt subtitle file.
        draft_name: Name for the CapCut draft.
        width: Canvas width.
        height: Canvas height.
        capcut_drafts_folder: Path to CapCut drafts folder.

    Returns:
        Dict with draft info, or None if pycapcut unavailable.
    """
    try:
        from jusads_compliance.capcut_client import (
            CAPCUT_AVAILABLE,
            create_multi_scene_draft,
        )
    except ImportError:
        logger.warning("[VideoAssembler] capcut_client not available")
        return None

    if not CAPCUT_AVAILABLE:
        logger.info("[VideoAssembler] pyCapCut not installed — skipping draft creation")
        return None

    # Filter to existing clips only
    valid_clips = [c for c in scene_clips if os.path.exists(c)]
    if not valid_clips:
        return None

    # Create the multi-scene draft
    result = create_multi_scene_draft(
        scene_clips=valid_clips,
        audio_path=audio_path,
        subtitles_srt=subtitles_srt,
        draft_name=draft_name,
        width=width,
        height=height,
        capcut_drafts_folder=capcut_drafts_folder,
    )

    if result:
        logger.info(
            "[VideoAssembler] CapCut draft created: '%s' (%d scenes)",
            draft_name, len(valid_clips),
        )

    return result


# ─────────────────────────────────────────────────────────────────────────────
# Dual Output — convenience function for both paths
# ─────────────────────────────────────────────────────────────────────────────


async def assemble_dual_output(
    scene_clips: list[str],
    scenes: list[dict],
    audio_path: Optional[str] = None,
    subtitles_srt: Optional[str] = None,
    draft_name: str = "ai_video_ad",
    width: int = 1080,
    height: int = 1920,
    capcut_drafts_folder: Optional[str] = None,
) -> dict:
    """Produce both FFmpeg .mp4 AND CapCut draft from the same scene clips.

    This is the main entry point for dual-output video assembly.
    The AI plans the edits, then both renderers execute.

    Args:
        scene_clips: Ordered list of rendered scene clip paths.
        scenes: Scene metadata (descriptions, subtitles, durations).
        audio_path: Optional voiceover audio.
        subtitles_srt: Optional .srt file.
        draft_name: CapCut draft name.
        width/height: Canvas dimensions.
        capcut_drafts_folder: CapCut drafts location.

    Returns:
        Dict with:
          - mp4_path: Path to the rendered .mp4 (or None)
          - capcut_draft: Dict with draft info (or None)
          - edit_plan: The AI's edit decisions
    """
    # Step 1: AI decides what edits to apply
    edit_plan = await plan_edits(scenes)

    # Step 2: FFmpeg renders instant .mp4
    mp4_path = assemble_ffmpeg(scene_clips, edit_plan, audio_path)

    # Step 3: CapCut draft for user editing
    capcut_draft = assemble_capcut_draft(
        scene_clips=scene_clips,
        edit_plan=edit_plan,
        scenes=scenes,
        audio_path=audio_path,
        subtitles_srt=subtitles_srt,
        draft_name=draft_name,
        width=width,
        height=height,
        capcut_drafts_folder=capcut_drafts_folder,
    )

    logger.info(
        "[VideoAssembler] Dual output: mp4=%s, capcut=%s",
        "YES" if mp4_path else "NO",
        "YES" if capcut_draft else "NO",
    )

    return {
        "mp4_path": mp4_path,
        "capcut_draft": capcut_draft,
        "edit_plan": edit_plan,
    }
